apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
  labels:
    name: demo
spec:
  containers:
    - name: html-v1
      image: kart10/kart10:hello3
      envFrom:
      - configMapRef:
          name: cm-example